apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmaps/backend.yaml
  - secrets/mongo.yaml
  - storage/mongo.yaml
  - deployments/mongo.yaml
  - deployments/backend.yaml
  - deployments/frontend.yaml
  - services/mongo.yaml
  - services/backend.yaml
  - services/frontend.yaml
